modules/admin/controllers/UserController.php
<?php

namespace sadovojav\user\modules\admin\controllers;

use Yii;
use yii\base\Model;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use sadovojav\user\models\User;
use yii\web\BadRequestHttpException;
use sadovojav\user\models\UserSearch;
use sadovojav\user\models\UserConfig;
use sadovojav\user\models\UserProfile;

/**
 * Class UserController
 * @package backend\controllers
 */
class UserController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'delete', 'delete-multiple', 'change-status'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['backend']
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'delete-multiple' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $user = new User();
        $user->setScenario('insert');

        $profile = new UserProfile();

        if ($user->load(Yii::$app->request->post()) && $profile->load(Yii::$app->request->post())) {
            if (Model::validateMultiple([$user, $profile])) {
                $user->save(false);

                $user->link('profile', $profile);

                return $this->redirect(['view', 'id' => $user->id]);
            }
        }

        return $this->render('create', [
            'user' => $user,
            'profile' => $profile
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if (!Yii::$app->user->can('updateOwnProfile', ['profileId' => $id])) {
            throw new ForbiddenHttpException;
        }

        $user = $this->findModel($id);

        if ($user->load(Yii::$app->request->post()) && $user->profile->load(Yii::$app->request->post())) {
            if (Model::validateMultiple([$user, $user->profile])) {
                $user->save(false);

                $user->link('profile', $user->profile);

                return $this->redirect(['view', 'id' => $user->id]);
            }
        }

        return $this->render('create', [
            'user' => $user,
            'profile' => $user->profile
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (Yii::$app->user->id == $id) {
            throw new ForbiddenHttpException;
        }

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing User models.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @return mixed
     */
    public function actionDeleteMultiple()
    {
        $pks = Yii::$app->request->post('pks');

        if (!$pks) {
            return false;
        }

        return User::deleteAll(['id' => $pks]);
    }

    /**
     * Cache status to User models.
     * @return bool|int
     */
    public function actionChangeStatus()
    {
        $pks = Yii::$app->request->post('pks');

        if (!$pks) {
            return false;
        }

        return User::updateAll(['status' => Yii::$app->request->post('status')], ['id' => $pks]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/admin/views/user/_form.php
<?php

use yii\helpers\Html;
use sadovojav\user\Module;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;
use sadovojav\user\models\User;
use kartik\widgets\SwitchInput;

?>

<div class="user-form">
    <?php $form = ActiveForm::begin([
        'options' => [
            'enctype' => 'multipart/form-data'
        ]
    ]); ?>

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title"><?= $user->username; ?></h3>

            <div class="box-tools pull-right">
                <?= Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'], [
                    'title' => Module::t('user', 'Create'),
                    'class' => 'btn btn-box-tool'
                ]); ?>
                <?= Html::submitButton('<i class="glyphicon glyphicon-floppy-disk"></i>', [
                    'title' => Module::t('user', 'Save'),
                    'class' => 'btn btn-box-tool',
                ]); ?>
                <?php if (!$user->isNewRecord) : ?>
                    <?= Html::a('<i class="glyphicon glyphicon-trash"></i>', ['delete', 'id' => $user->id], [
                        'title' => Module::t('user', 'Delete'),
                        'class' => 'btn btn-box-tool',
                        'data' => [
                            'confirm' => Module::t('user', 'Delete item'),
                            'method' => 'post',
                        ],
                    ]); ?>
                <?php endif; ?>
            </div>
        </div>

        <div class="box-body">
            <div class="row">
                <div class="col-md-6">
                    <?= $form->field($user, 'username')->textInput([
                        'maxlength' => 32,
                        'disabled' => !$user->isNewRecord
                    ]); ?>

                    <div class="row">
                        <div class="col-sm-6">
                            <?= $form->field($profile, 'name_first')->textInput([
                                'maxlength' => 50
                            ]); ?>
                        </div>

                        <div class="col-sm-6">
                            <?= $form->field($profile, 'name_last')->textInput([
                                'maxlength' => 50
                            ]); ?>
                        </div>
                    </div>

                    <?= $form->field($user, 'email')->textInput([
                        'maxlength' => 32
                    ]); ?>

                    <?= $form->field($user, 'role')->widget(Select2::classname(), [
                        'data' => User::getRoles(),
                        'options' => [
                            'placeholder' => ''
                        ],
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                    ]); ?>
                </div>

                <div class="col-md-6">
                    <?= $form->field($user, 'auth_key')->textInput([
                        'maxlength' => 255,
                        'disabled' => !$user->isNewRecord
                    ]); ?>

                    <?= $form->field($user, 'password')->passwordInput([
                        'maxlength' => 255,
                        'value' => ''
                    ]); ?>

                    <?= $form->field($user, 'passwordRepeat')->passwordInput([
                        'maxlength' => 255,
                        'value' => ''
                    ]); ?>

                    <?= $form->field($user, 'status')->widget(SwitchInput::className(), [
                        'pluginOptions' => [
                            'size' => 'small',
                            'onColor' => 'success',
                            'offColor' => 'danger',
                        ]
                    ]); ?>
                </div>
            </div>
        </div>

        <div class="box-footer">
            <div class="text-right">
                <?= Html::submitButton(Module::t('user', 'Save'), [
                    'class' => 'btn btn-primary btn-sm'
                ]); ?>
            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

modules/admin/views/user/create.php
<?php

use sadovojav\user\Module;

$this->title = Module::t('user', 'Create');
$this->params['breadcrumbs'] = [
    ['label' => Module::t('user', 'Users'), 'url' => ['index']],
    $this->title,
];

?>

<div class="user-create">
    <?= $this->render('_form', [
        'user' => $user,
        'profile' => $profile,
    ]); ?>
</div>

modules/admin/views/user/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use sadovojav\user\Module;
use sadovojav\user\models\User;
use sadovojav\user\modules\admin\AssetBundle;

AssetBundle::register($this);

$this->title = Module::t('user', 'User manager');
$this->params['breadcrumbs'] = [
    $this->title,
];

?>

<div class="user-index">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'panel' => [
            'type' => GridView::TYPE_DEFAULT,
            'heading' => false
        ],
        'toolbar' => [
            ['content' =>
                Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'], [
                    'title' => Module::t('user', 'Create'),
                    'class' => 'btn btn-box-tool'
                ]) . ' ' .
                Html::a('<i class="glyphicon glyphicon-repeat"></i>', [
                    'index'
                ], [
                    'data-pjax' => 0,
                    'title' => Module::t('user', 'Reset'),
                    'class' => 'btn btn-box-tool',
                ]) . ' ' .
                Html::a('<i class="glyphicon glyphicon-ok-circle"></i>', [
                    'index'
                ], [
                    'title' => Module::t('user', 'Active'),
                    'class' => 'btn btn-box-tool',
                    'data-action' => 'change-status',
                    'data-status' => 1,
                    'data-url' => Yii::$app->urlManager->createUrl(['/user/change-status'])
                ]) . ' ' .
                Html::a('<i class="glyphicon glyphicon-remove-circle"></i>', [
                    'index'
                ], [
                    'title' => Module::t('user', 'Inactive'),
                    'class' => 'btn btn-box-tool',
                    'data-action' => 'change-status',
                    'data-status' => 0,
                    'data-url' => Yii::$app->urlManager->createUrl(['/user/change-status'])
                ]) . ' ' .
                Html::a('<i class="glyphicon glyphicon-trash"></i>', [
                    'index'
                ], [
                    'title' => Module::t('user', 'Delete'),
                    'class' => 'btn btn-box-tool',
                    'data-action' => 'delete-multiple',
                    'data-title' => Module::t('user', 'Delete items'),
                    'data-url' => Yii::$app->urlManager->createUrl(['/user/delete-multiple'])
                ])
            ],
//            '{toggleData}'
        ],
        'export' => false,
        'pjax' => true,
        'condensed' => true,
        'bordered' => true,
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],
            [
                'attribute' => 'id',
                'width' => '75px'
            ],
            'username',
//            'email',
//			'auth_key',
//			'password',
            [
                'attribute' => 'role',
                'value' => 'roleName',
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => User::getRoles(),
                'filterWidgetOptions' => [
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ],
                'filterInputOptions' => [
                    'placeholder' => '-'
                ],
            ],
            [
                'class' => 'kartik\grid\BooleanColumn',
                'attribute' => 'status',
                'vAlign' => 'middle',
            ],
//			'created_at',
//			'updated_at',
            [
                'class' => 'kartik\grid\ActionColumn',
                'vAlign' => 'middle',
            ],
            [
                'class' => 'kartik\grid\CheckboxColumn',
                'headerOptions' => [
                    'class' => 'kartik-sheet-style'
                ],
            ],
        ],
    ]); ?>
</div>

modules/admin/views/user/update.php
<?php

use sadovojav\user\Module;

$this->title = $user->username;
$this->params['breadcrumbs'] = [
    ['label' => Module::t('user', 'Users'), 'url' => ['index']],
    ['label' => $user->username, 'url' => ['view', 'id' => $user->id]],
    Module::t('user', 'Update'),
];

?>

<div class="user-update">
    <?= $this->render('_form', [
        'user' => $user,
        'profile' => $profile
    ]); ?>
</div>

modules/admin/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use sadovojav\user\Module;

$this->title = Module::t('user', 'View');
$this->params['breadcrumbs'] = [
    ['label' => Module::t('user', 'Users'), 'url' => ['index']],
    $this->title,
];

?>

<div class="user-view">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title"><?= $model->username; ?></h3>

            <div class="box-tools pull-right">
                <?= Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'], [
                    'title' => Module::t('user', 'Create'),
                    'class' => 'btn btn-box-tool'
                ]); ?>
                <?= Html::a('<i class="glyphicon glyphicon-pencil"></i>', ['update', 'id' => $model->id], [
                    'title' => Module::t('user', 'Update'),
                    'class' => 'btn btn-box-tool'
                ]); ?>
                <?= Html::a('<i class="glyphicon glyphicon-trash"></i>', ['delete', 'id' => $model->id], [
                    'title' => Module::t('user', 'Delete'),
                    'class' => 'btn btn-box-tool',
                    'data' => [
                        'confirm' => Module::t('user', 'Are you sure you want to delete this items?'),
                        'method' => 'post',
                    ],
                ]); ?>
            </div>
        </div>

        <div class="box-body">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    'username',
                    'profile.name_first',
                    'profile.name_last',
                    'email:email',
//                    'auth_key',
//                    'password',
                    [
                        'attribute' => 'role',
                        'value' => $model->roleName
                    ],
                    'status:boolean',
                    'created_at',
                    'updated_at',
                ],
            ]); ?>
        </div>
    </div>
</div>